[features]
seeds = false
[programs.localnet]
switchboardv2_vrf_example = "Cm9NgrNBLNJsED3GV3dZTLRYmhPQvQWyaFyUrvWPAzdb"

[registry]
url = "https://anchor.projectserum.com"

[provider]
#cluster = "localnet"
#wallet = "/Users/daiwanwei/.config/solana/id.json"
cluster = "devnet"
wallet = "secrets/payer-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
